name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4.2.0
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Cache Maven packages
        uses: actions/cache@v4.1.0
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Set up JDK
        uses: actions/setup-java@v4.4.0
        with:
          java-version: 21
          distribution: 'adopt'
          cache: maven

      - name: Build
        run: mvn -B verify -pl !:docs -P container

      - name: Publish container
        run: |
          echo "${ACR_PASSWORD}" | docker login ${ACR_HOSTNAME} --username ${ACR_USERNAME} --password-stdin
          docker tag traqqr:latest ${ACR_HOSTNAME}/traqqr:latest
          docker push ${ACR_HOSTNAME}/traqqr:latest
        env:
          ACR_HOSTNAME: ${{ secrets.ACR_HOSTNAME }}
          ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
          ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
        if: ${{ github.ref == 'refs/heads/main' }}
